### ISSUE TITLE
XSS 漏洞

### ISSUE THREAD

**Issue by SCLeoX** [librian-center/librian-center-frontend#3]
呐，在大多数情况下，尤其是参数是用户提供的情况下，都不应该使用 `.html` 噢~

不信的的话，请看这里：https://center.librian.it/?%E4%BA%BA=Rin&%E4%BA%8B%E4%BB%B6=88b238f4-b06e-11ea-96d9-00155d2eced1#%E8%AF%BB%E6%96%87%E7%AB%A0 。

嘛，人家已经给你修好了：https://github.com/librian-center/librian-center-frontend/pull/2。

（好的，装萝莉过分困难，我不装了）

超量召唤：Bug x1 +（假）萝莉 x1 → @RimoChan → 闪光 @RimoChan 一 → 闪光 @RimoChan · 电光皇

**Comment by RimoChan** [comment]
奇怪我下午刚写出的BUG你怎么改得这么快2333

**Comment by SCLeoX** [comment]
> 奇怪我下午刚写出的BUG你怎么改得这么快2333

你那个 commit 一发我就一直盯着等你部署（

**Comment by RimoChan** [comment]
不不，我奇怪的是你没有watch为什么会注意到我commit了？？？

**Comment by SCLeoX** [comment]
> 不不，我奇怪的是你没有watch为什么会注意到我commit了？？？

因为我太关心你了，每天盯着你看。

**Comment by SCLeoX** [comment]
（其实我也忘了怎么注意到的
